#
# Copyright (c) 2017 Paweł Jarosz <paweljarosz3691@gmail.com>
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifndef CONFIG_TPL_BUILD
obj-y += clk_rk3066.o
obj-y += syscon_rk3066.o
else
obj-y += sdram_init.o
endif
